package com.conecta.conectagraxa.service;

import org.springframework.stereotype.Service;

@Service
public class CandidaturasService {

	// EMPRESA VISUALIZAR CANDIDATURAS DA VAGA

	// PROFISSIONAL CANDIDATAR NA VAGA

	// PROFISSIONAL VISUALIZAR VAGAS CANDIDATADAS

	// EMPRESA VISUALIZAR FEED PROFISSIONAL CANDIDATADO NA VAGA

	// PROFISSIONAL VISUALIZAR FEED EMPRESA CANDIDATADA

}
